import cssLayout from './globals.css';
import styles from './home.module.css'
import Home from './page';
import header from './components/header/header';

export const metadata = {
  title: "Clash At Carleton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
        rel="icon"
        href="/assets/darkBG.png"
        type="image/<generated>"
        sizes="<generated>"
      />
      </head>
      <body>{children}</body>
    </html>
  );
}
